# .github/workflows/nextjs.yml
name: Deploy Next.js site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          # ...(省略)...

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # または ${{ steps.detect-package-manager.outputs.manager }}

      # - name: Setup Pages # configure-pages は next.config.js で設定するので不要な可能性
      #   uses: actions/configure-pages@v5

      # - name: Restore cache # setup-node で cache: npm を使えば不要な場合も
      #   uses: actions/cache@v4
      #   with:
      #     # ...(省略)...

      - name: Install dependencies
        run: npm ci # または ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build with Next.js
        env:
          NODE_ENV: production # ★ production モードを明示
          # GITHUB_REPOSITORY は自動で利用可能なので、ここで設定不要
        run: npm run build # または ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4